// Module included in the following assemblies:
//
// * machine_management/deploying-machine-health-checks.adoc
// * post_installation_configuration/node-tasks.adoc

[id="machine-health-checks-about_{context}"]
= About MachineHealthChecks

A MachineHealthCheck is a resource which allows users to define conditions under
which Machines within a Cluster should be considered unhealthy and should be
automatically remediated.

When defining a MachineHealthCheck, users specify conditions to check for and a
timeout for each of the conditions.
If any of these conditions is met on the Machine's Node for the duration of the timeout,
the Machine will be remediated.
The action of remediating a Machine will trigger a new Machine to be created,
to replace the failed one.

For example, you may set a condition such as staying in the `NotReady` state
for 15 minutes or displaying a permanent condition in the node-problem-detector.

[NOTE]
====
Please note that MachineHealthChecks currently *only* support Machines that are
owned by a MachineSet.
Please review the <<machine-health-checks-limitations_{context}>> below for
full details of MachineHealthCheck limitations.
====

When a Machine is deleted, you will see a `machine deleted` event.
To limit disruptive impact of the Machine deletion, if there are more unhealthy
Machines than the `maxUnhealthy` threshold allows for in the targeted pool of Machines,
remediation stops so that manual intervention can take place.

[id="machine-health-checks-limitations_{context}"]
== Limitations when deploying MachineHealthChecks

There are limitations to consider before deploying a MachineHealthCheck:

* Only Machines owned by a MachineSet are remediated by a MachineHealthCheck.
* Control Plane Machines are not currently supported and are not remediated if they are unhealthy.
* If the node for a Machine is removed from the cluster, a MachineHealthCheck considers the Machine to be unhealthy and remediates it immediately.
* If a node does not join the cluster for a Machine after the `nodeStartupTimeout`, the Machine is remediated.
* If a Machine fails for any reason (the phase is `Failed`), the Machine is remediated immediately.
